name: Deploy Allure Report

on:
  workflow_run:
    workflows: ["Tests CI Pipeline"]
    types: [completed]
    branches: [main]

jobs:
  deploy-allure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-ubuntu-firefox
          path: allure-results/ubuntu-firefox

      - name: Download Windows results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-windows-chrome
          path: allure-results/windows-chrome

      - name: Download macOS results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-macos-safari
          path: allure-results/macos-safari

      - name: Setup Allure
        run: |
          curl -o allure-2.27.0.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          sudo tar -zxvf allure-2.27.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure

      - name: Generate Allure report
        run: |
          # Объединение результатов всех job'ов
          mkdir -p combined-results
          find allure-results -name "*.json" -exec cp {} combined-results/ \;
          find allure-results -name "*.xml" -exec cp {} combined-results/ \;
          
          # Генерация отчета
          allure generate combined-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: allure-report
